import java.awt.Color;
import java.awt.Graphics;
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author wassil
 */
public class ClassementDlg extends javax.swing.JDialog {
    private LesJoueurs lesJo;
    private LesParties lesPa;
    private int tabC[]; // utilisé pour le classement des joueurs et pour les trier

    /**
     * Creates new form ClassementDlg
     */
    public ClassementDlg(java.awt.Frame parent, boolean modal, LesJoueurs lesj, LesParties lp) {
        super(parent, modal);
        initComponents(); // costructeur de la classe JDialog
        this.lesJo = lesj;
        this.lesPa = lp;
        Edition.setText(this.lesJo.toString());
        this.tabC = new int [this.lesJo.getNbJoueurs()]; // allocation d'espace pour le tableau
        initClassement();
        initListeJoueursClasses(); // rempli la JList, avec les pseudos des joueurs dans l'ordre
    }

    private void initClassement(){ // On fais un classement avec les indices des joueurs ayant le plus de victoires placés au début
        int max;
        for(int i=0; i<this.lesJo.getNbJoueurs(); i++){ // Initialisation du tableau avec les indices de chaque joueurs
            tabC[i]=i;
        }
        for(int i=0; i<tabC.length-1; i++){ // Pour chaque position de i, on cherche l'indice du joueur ayant le plus de victoires parmi ceux qui le succède
            max = i;
            for(int j=i+1; j<tabC.length; j++){
                if(this.lesJo.getJoueur(tabC[j]).getNbpartiesGagnees()>this.lesJo.getJoueur(tabC[max]).getNbpartiesGagnees()){ // Si un joueur à plus de victoires que max, on le garde comme nouveau max
                    max = j;
                }
            }
            if(max != i){ // Une fois le meilleur trouvé, on l'échange à la position actuel de i 
                int temp = tabC[i];
                tabC[i] = tabC[max];
                tabC[max] = temp;
            }
        }
    }
    
    @Override
    public void paint(Graphics g){
        // redessiner la fenêtre lors d'un rafraichissement
        // elle peut être appellée par la méthode repaint()
        super.paint(g); // appelle la méthode de la classe JDialog
        dessineHisto(); // pour dessiner l'histogramme
    }
    
    private void initListeJoueursClasses(){
        DefaultListModel mod = new DefaultListModel();
        this.ListeClassement.setModel(mod);
        for(int i=0; i<this.lesJo.getNbJoueurs(); i++){
            mod.addElement(""+(i+1)+" "+this.lesJo.getJoueur(tabC[i]).getPseudo());
        }
    }
    
    private void dessineHisto(){ // qui trace l'histogramme dans le panneau
        Graphics g = PanHisto.getGraphics(); // Graphics contient les méthodes de dessin et PanHisto JPanel de dessin de l'histo
        int nbJo = lesJo.getNbJoueurs(); // le nombre de joueurs
        int nbPa = lesPa.getNbPartie();
        int largeurMax = this.getWidth()/2-50;// largeur de la fenêtre /2 et -50 pour ne pas que l'affichage dépasse le panel
        int decalageLarg = 50; // pour positionner l'histogramme 
        int decalageHaut = 50; // pour positionner l'histogramme
        int largRect = largeurMax/nbJo; // largeur d'une barre de l'histogramme
        int hautMax = this.PanHisto.getHeight()/2;
        for(int i=0; i<nbJo; i++){
            Joueur j = this.lesJo.getJoueur(i);
            int nbPartG = j.getNbpartiesGagnees();
            int hautRectJ; // hauteur de la barre du rectangle pour le joueur j
            if(nbPartG == 0){
                hautRectJ = 10; // 10 pixels si pas de parties gagnés
            }
            else{
                hautRectJ = hautMax*nbPartG/nbPa;
            }
            // la hauteur est proportionnelle au nombre de parties gagnées
            int r = (int) (Math.random()*255);
            int v = (int) (Math.random()*255);
            int b = (int) (Math.random()*255);
            // on fixe la couleur du tracé
            g.setColor(new Color(r,v,b));
            // ecriture du nom du joueur
            g.drawString(j.getPseudo(),i*largRect+decalageLarg,hautMax+decalageHaut+20);
            // ecriture du nombre de parties gagnées par le joueur
            g.drawString(""+nbPartG,i*largRect+decalageLarg,hautMax+decalageHaut+30);
            //tracé de la barre de l'histogramme pour le joueur
            g.fillRect(i*largRect+decalageLarg,hautMax+decalageHaut-hautRectJ,largRect,hautRectJ);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHaut = new javax.swing.JPanel();
        Titre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PanHisto = new javax.swing.JPanel();
        PDroit = new javax.swing.JPanel();
        TClassement = new javax.swing.JLabel();
        PDHaut = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListeClassement = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Titre.setText("Statistiques joueurs");
        PHaut.add(Titre);

        getContentPane().add(PHaut, java.awt.BorderLayout.NORTH);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PanHisto.setLayout(new java.awt.GridLayout(1, 1));
        PCentre.add(PanHisto);

        PDroit.setLayout(new java.awt.BorderLayout());

        TClassement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TClassement.setText("Classement des joueurs");
        TClassement.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        PDroit.add(TClassement, java.awt.BorderLayout.NORTH);

        PDHaut.setLayout(new java.awt.GridLayout(2, 1));

        jScrollPane1.setViewportView(ListeClassement);

        PDHaut.add(jScrollPane1);

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane2.setViewportView(Edition);

        PDHaut.add(jScrollPane2);

        PDroit.add(PDHaut, java.awt.BorderLayout.CENTER);

        PCentre.add(PDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassementDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        LesJoueurs lesj = new LesJoueurs();
        LesParties lp = new LesParties();

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClassementDlg dialog = new ClassementDlg(new javax.swing.JFrame(), true, lesj, lp);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JList<String> ListeClassement;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PDHaut;
    private javax.swing.JPanel PDroit;
    private javax.swing.JPanel PHaut;
    private javax.swing.JPanel PanHisto;
    private javax.swing.JLabel TClassement;
    private javax.swing.JLabel Titre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
