import java.awt.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author zeelu
 */
public class PanneauImage extends javax.swing.JPanel {
    private Image img; // stocke l'image à afficher dans le panneau
    /**
     * Creates new form PanneauImage
     */
    public PanneauImage() { // initisialise img à null
        super();
        this.img = null;
    }
    
    public PanneauImage(Image im){ // initialise img avec une image donnée en paramètre
        super();
        this.img = im;
    }
    
    public Image getImage(){
        return this.img;
    }
    
    public void setImage(Image im){
        this.img = im;
        this.repaint();
    }
    
    @Override
    public void paint(Graphics g){ // affiche l'image dans le panneau en redimensionnant celle-ci à la taille du panneau
        // On surcharge la méthode car on veut personnaliser l'affichage de l'image à la place de l'affichage par défaut 
        super.paint(g);
        if(img != null){
            g.drawImage(img,0,0,this.getWidth(),this.getHeight(),this);
        }  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
