/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import java.io.*;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author wassil
 */
public class SaisieJoueurDlg extends javax.swing.JDialog {
    //attributs
    private Joueur nj; //nouveau
    private boolean ok; //Valide=true Annuler = False
    private ImageIcon photo;
    private BoutonImage boutonImage; // pour afficher la photo du joueur dans un BouttonImage (bouton)
    /**
     * Creates new form SaisieJoueurDlg
     */
    public SaisieJoueurDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);// appel du constructeur (avec paramètre) de la classe ancêtre
        initComponents();// constructeur de l’interface par l’EDI
        // initialisation des attributs
        this.nj = new Joueur();//photo du joueur par défaut
        this.ok = false;
        boutonImage = new BoutonImage(this.nj.getPhoto().getImage());
        PPhoto.removeAll(); // On enlève le bouton BPhoto du panel PPhoto
        PPhoto.setLayout(new GridLayout(1,1)); 
        PPhoto.add(this.boutonImage); // On ajoute le BoutonImage dans le panel BPhoto
    }
    //accesseur get pour le joueur et pour ok
    public Joueur getJoueur(){
        return this.nj;
    }
    public boolean getOK(){
        return this.ok;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHaut = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        PCGauche = new javax.swing.JPanel();
        LPseudo = new javax.swing.JLabel();
        PVIde = new javax.swing.JPanel();
        LPhoto = new javax.swing.JLabel();
        BParcourir = new javax.swing.JButton();
        PCDroit = new javax.swing.JPanel();
        PPseudo = new javax.swing.JPanel();
        Pseudo = new javax.swing.JTextField();
        PPhoto = new javax.swing.JPanel();
        BPhoto = new javax.swing.JButton();
        PBas = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ajout d'un nouveau joueur");
        PHaut.add(jLabel1);

        getContentPane().add(PHaut, java.awt.BorderLayout.NORTH);

        PCentre.setLayout(new java.awt.GridLayout(1, 2));

        PCGauche.setLayout(new java.awt.GridLayout(2, 2));

        LPseudo.setText("Pseudo?");
        PCGauche.add(LPseudo);
        PCGauche.add(PVIde);

        LPhoto.setText("Photo ?");
        PCGauche.add(LPhoto);

        BParcourir.setText("Parcourir");
        BParcourir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BParcourirActionPerformed(evt);
            }
        });
        PCGauche.add(BParcourir);

        PCentre.add(PCGauche);

        PCDroit.setLayout(new java.awt.GridLayout(2, 1));

        PPseudo.setLayout(new java.awt.GridLayout(1, 1));
        PPseudo.add(Pseudo);

        PCDroit.add(PPseudo);

        PPhoto.setLayout(new java.awt.GridLayout(1, 1));
        PPhoto.add(BPhoto);

        PCDroit.add(PPhoto);

        PCentre.add(PCDroit);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        PBas.add(BValider);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        PBas.add(BAnnuler);

        getContentPane().add(PBas, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok = false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BAnnulerActionPerformed

    private void BParcourirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BParcourirActionPerformed
        // TODO add your handling code here:
        // récupère un fichier et va crée une ImageIcon
        // qui sous-affecte à l’attribut this.photo
        // et affichage sur le bouton BPhoto
        JFileChooser jf= new JFileChooser();
        if (jf.showOpenDialog(this)== JFileChooser.APPROVE_OPTION){
            String path = jf.getSelectedFile().getPath();
            Image img=Toolkit.getDefaultToolkit().getImage(path);
            this.photo = new ImageIcon(img);
            boutonImage.setImage(img); // mise à jour du BoutonImage
        }
    }//GEN-LAST:event_BParcourirActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        nj.setPseudo(Pseudo.getText()); // Pseudo ← JTextField
        if(this.photo!=null){
            nj.setPhoto(this.photo); // photo ← attribut de type ImageIcon
        }
        else{
            nj.setPhoto(new ImageIcon(getClass().getResource("/joueurDefaut.png")));
        }
        this.ok = true; // fermeture par Valider
        this.setVisible(false); // fermeture de la boite
        this.dispose(); // pour la gestion mémoire
    }//GEN-LAST:event_BValiderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisieJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SaisieJoueurDlg dialog = new SaisieJoueurDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BParcourir;
    private javax.swing.JButton BPhoto;
    private javax.swing.JButton BValider;
    private javax.swing.JLabel LPhoto;
    private javax.swing.JLabel LPseudo;
    private javax.swing.JPanel PBas;
    private javax.swing.JPanel PCDroit;
    private javax.swing.JPanel PCGauche;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PHaut;
    private javax.swing.JPanel PPhoto;
    private javax.swing.JPanel PPseudo;
    private javax.swing.JPanel PVIde;
    private javax.swing.JTextField Pseudo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
