
import javax.swing.DefaultListModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author zeelu
 */
public class SelectionJoueursDlg extends javax.swing.JDialog {
    
    private Joueur joueur1;
    private Joueur joueur2;
    private LesJoueurs lj;
    private boolean ok;
    
    /**
     * Creates new form SelectionJoueursDlg
     */
    public SelectionJoueursDlg(java.awt.Frame parent, boolean modal, LesJoueurs lj) {
        super(parent, modal);
        initComponents();
        this.joueur1 = null;
        this.joueur2 = null;
        this.lj = lj;
        initListesJoueurs();
        this.ok = false;
    }

    public Joueur getJoueur1() {
        return joueur1;
    }

    public Joueur getJoueur2() {
        return joueur2;
    }

    public boolean getOK() {
        return ok;
    }
    
    private void initListesJoueurs(){
        // rempli la JList avec les pseudos des joueurs
        // usage d'un modèle
        DefaultListModel mod = new DefaultListModel();
        LJoueursDispo.setModel(mod);
        for(int i=0; i<this.lj.getNbJoueurs(); i++){
            mod.addElement(this.lj.getJoueur(i).getPseudo());
            DefaultListModel mod2 = new DefaultListModel();
            LJoueurs.setModel(mod2);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PHaut = new javax.swing.JPanel();
        LTitre = new javax.swing.JLabel();
        PCentre = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        LJoueursDispo = new javax.swing.JList<>();
        PSelection = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BAjout = new javax.swing.JButton();
        BRetrait = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        LJoueurs = new javax.swing.JList<>();
        PBas = new javax.swing.JPanel();
        BValider = new javax.swing.JButton();
        BAnnuler = new javax.swing.JButton();
        LMessage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LTitre.setText("Sélection des deux joueurs");
        PHaut.add(LTitre);

        getContentPane().add(PHaut, java.awt.BorderLayout.NORTH);

        PCentre.setLayout(new java.awt.GridLayout(1, 3));

        LJoueursDispo.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(LJoueursDispo);

        PCentre.add(jScrollPane1);

        PSelection.setLayout(new java.awt.GridLayout(4, 1));
        PSelection.add(jPanel1);

        BAjout.setText("==>>");
        BAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAjoutActionPerformed(evt);
            }
        });
        PSelection.add(BAjout);

        BRetrait.setText("<<==");
        BRetrait.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRetraitActionPerformed(evt);
            }
        });
        PSelection.add(BRetrait);
        PSelection.add(jPanel2);

        PCentre.add(PSelection);

        jScrollPane2.setViewportView(LJoueurs);

        PCentre.add(jScrollPane2);

        getContentPane().add(PCentre, java.awt.BorderLayout.CENTER);

        BValider.setText("Valider");
        BValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BValiderActionPerformed(evt);
            }
        });
        PBas.add(BValider);

        BAnnuler.setText("Annuler");
        BAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAnnulerActionPerformed(evt);
            }
        });
        PBas.add(BAnnuler);

        LMessage.setText(" ");
        PBas.add(LMessage);

        getContentPane().add(PBas, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAjoutActionPerformed
        // TODO add your handling code here:
        // récupération de l'indice sélectionné
        int ind = this.LJoueursDispo.getSelectedIndex();
        if(ind != 1){ // on vérifie qu'un élément est sélectionné
            // on vérifie qu'il n'y a pas déja 2 joueurs sélectionnés
            if(LJoueurs.getModel().getSize()<2){ // récupération du pseudo sélectionné
                String ps = LJoueursDispo.getSelectedValue();
                DefaultListModel mod1 = (DefaultListModel) LJoueursDispo.getModel();
                DefaultListModel mod2 = (DefaultListModel) LJoueurs.getModel();
                mod1.remove(ind);
                mod2.addElement(ps);
            }
        }
    }//GEN-LAST:event_BAjoutActionPerformed

    private void BRetraitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRetraitActionPerformed
        // TODO add your handling code here:
        int ind = this.LJoueurs.getSelectedIndex();
        if(ind != -1){ // il y a une selection
            String ps = LJoueurs.getSelectedValue();
            DefaultListModel mod1 = (DefaultListModel)this.LJoueursDispo.getModel();
            DefaultListModel mod2 = (DefaultListModel)this.LJoueurs.getModel();
            // on déplace le nom du pseudo
            mod1.addElement(ps);
            mod2.remove(ind); // supprime lélément à cet indice
        }
    }//GEN-LAST:event_BRetraitActionPerformed

    private void BValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BValiderActionPerformed
        // TODO add your handling code here:
        // on vérifie qu'il y a 2 joueurs dans la liste LJoueurs(JList)
        if(LJoueurs.getModel().getSize()==2){
            String ps1 = LJoueurs.getModel().getElementAt(0); // 1ere élément
            String ps2 = LJoueurs.getModel().getElementAt(1); // 2eme élément
            this.joueur1 = this.lj.rechJoueur(ps1);
            this.joueur2 = this.lj.rechJoueur(ps2);
            this.ok = true;
            // fermeture de la boîte
            this.setVisible(false);
            this.dispose();
        }
        else{
            LMessage.setText("Il faut 2 joueurs!");
        }
    }//GEN-LAST:event_BValiderActionPerformed

    private void BAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAnnulerActionPerformed
        // TODO add your handling code here:
        this.ok = false;
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_BAnnulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectionJoueursDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        LesJoueurs lj = new LesJoueurs();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SelectionJoueursDlg dialog = new SelectionJoueursDlg(new javax.swing.JFrame(), true, lj);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BAjout;
    private javax.swing.JButton BAnnuler;
    private javax.swing.JButton BRetrait;
    private javax.swing.JButton BValider;
    private javax.swing.JList<String> LJoueurs;
    private javax.swing.JList<String> LJoueursDispo;
    private javax.swing.JLabel LMessage;
    private javax.swing.JLabel LTitre;
    private javax.swing.JPanel PBas;
    private javax.swing.JPanel PCentre;
    private javax.swing.JPanel PHaut;
    private javax.swing.JPanel PSelection;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
