/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
import java.io.*;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.*;
import java.awt.*;
/**
 *
 * @author zeelu
 */
public class VisuJoueurDlg extends javax.swing.JDialog {
    //attributs
    private LesJoueurs lj; // tous les joueurs
    private Joueur joueurCourant; // celui dont les infos sont afficher le 1er au départ
    private PanneauImage panPhoto; // on ajoute un PanneauImage pour un meilleur affichage de la photo à la place d'un bouton
    /**
     * Creates new form VisuJoueurDlg
     */
    // constructeur
    public VisuJoueurDlg(java.awt.Frame parent, boolean modal, LesJoueurs llj) {
        super(parent, modal);
        initComponents();
        this.lj = llj;
        this.joueurCourant = this.lj.getJoueur(0);
        panPhoto = new PanneauImage(); // Création du nouveau panneau image
        PPhoto.add(panPhoto); // ajoute le Panneau Image au Panel PPhoto
        afficheJoueurCourant(); // pour afficher ses informations
        initListeJoueurs(); // pour remplir la liste déroulante avec le pseudo
    }
    
    private void initListeJoueurs(){
        for(int i = 0; i<this.lj.getNbJoueurs();i++){
            ListeJoueurs.addItem(this.lj.getJoueur(i).getPseudo()); // ListeJoueurs <-- JComboBar
        }
    }
    
    public void afficheJoueurCourant(){
        VPseudo.setText(this.joueurCourant.getPseudo());
        VNiveau.setText(""+this.joueurCourant.getNiveau());
        panPhoto.setImage(this.joueurCourant.getPhoto().getImage());
        Edition.setText(this.joueurCourant.toString()); //Edition <-- JTextArea
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ListeJoueurs = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        Pseudo = new javax.swing.JLabel();
        VPseudo = new javax.swing.JLabel();
        Niveau = new javax.swing.JLabel();
        VNiveau = new javax.swing.JLabel();
        PPhoto = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Edition = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Joueur à visualiser :");
        jPanel1.add(jLabel1);

        ListeJoueurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListeJoueursActionPerformed(evt);
            }
        });
        jPanel1.add(ListeJoueurs);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(1, 2));

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setLayout(new java.awt.GridLayout(2, 2));

        Pseudo.setText("Pseudo :");
        jPanel5.add(Pseudo);
        jPanel5.add(VPseudo);

        Niveau.setText("Niveau :");
        jPanel5.add(Niveau);
        jPanel5.add(VNiveau);

        jPanel3.add(jPanel5);

        PPhoto.setLayout(new java.awt.GridLayout(1, 1));
        jPanel3.add(PPhoto);

        jPanel2.add(jPanel3);

        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        Edition.setColumns(20);
        Edition.setRows(5);
        jScrollPane1.setViewportView(Edition);

        jPanel4.add(jScrollPane1);

        jPanel2.add(jPanel4);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ListeJoueursActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListeJoueursActionPerformed
        // TODO add your handling code here:
        int ind = ListeJoueurs.getSelectedIndex();
        this.joueurCourant = this.lj.getJoueur(ind);
        afficheJoueurCourant();
    }//GEN-LAST:event_ListeJoueursActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisuJoueurDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        LesJoueurs lj = new LesJoueurs();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisuJoueurDlg dialog = new VisuJoueurDlg(new javax.swing.JFrame(), true, lj );
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Edition;
    private javax.swing.JComboBox<String> ListeJoueurs;
    private javax.swing.JLabel Niveau;
    private javax.swing.JPanel PPhoto;
    private javax.swing.JLabel Pseudo;
    private javax.swing.JLabel VNiveau;
    private javax.swing.JLabel VPseudo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
